[package]
name = "sqlcrypto"
description = "lightweight and memory efficient sqlite/sqlcipher encryption (not secure)/decryption in pure rust"
license = "MIT"
version = "0.1.1"
authors = ["PizzaCrust <pizzacrustcoder@gmail.com>"]
edition = "2018"
repository = "https://github.com/PizzaCrust/sqlcrypto"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sqlcrypto"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "sqlcrypto-cli"
path = "src/main.rs"

[dependencies]
ring = "0.16.15"
aes_frast = "0.1.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.18"